# Generated by Django 3.0.2 on 2020-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200206_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
