# Generated by Django 3.0.2 on 2020-02-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200206_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='prc',
        ),
    ]
