# Generated by Django 3.0.2 on 2020-02-29 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ap', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('Bp', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ABp', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('Op', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('An', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('Bn', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ABn', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('On', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('Dob', models.DateField()),
                ('Blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='Male', max_length=3)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip_code', models.CharField(max_length=6)),
                ('Blood_Donated', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
