# Generated by Django 3.0.2 on 2020-02-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Blood_Donated',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
