# Generated by Django 3.0.2 on 2020-02-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200229_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Blood_Donated',
            field=models.IntegerField(default=0),
        ),
    ]
