# Generated by Django 3.0.2 on 2020-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200229_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='ABn',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='ABp',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='An',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='Ap',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='Bn',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='Bp',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='On',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='Op',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='Blood_Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='Blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='A+', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='A+', max_length=3),
        ),
    ]
